#!/usr/bin/env node
'use strict';

/**
 * Encrypts a JSON payload exactly the way the app does
 * (ResearchServerService._encrypt in wellbeing-mapper-app), so the server
 * and tools/decrypt_received.py can be exercised without a phone.
 *
 * Scheme: the payload is AES-256-GCM encrypted with a random key and a
 * random 16-byte IV (ciphertext with the 16-byte tag appended); the key is
 * wrapped with RSA-OAEP-SHA-256. As in the app, the RSA plaintext is the
 * *base64 text* of the AES key, not its raw bytes. The package is JSON,
 * base64-encoded as a whole.
 *
 * Usage:
 *   node tools/encrypt_sample.js --public-key public_key.pem [--type initial|biweekly|consent]
 *        [--payload payload.json] [--submission-id <64 hex>|auto]
 * Prints the request body for the matching upload endpoint.
 */

const crypto = require('crypto');
const fs = require('fs');

const ALGORITHM = 'AES-256-GCM+RSA-OAEP-SHA256';

/** Returns the base64 package string the app sends as `encrypted_data`. */
function encryptPackage(payload, publicKeyPem, { researchSite = 'wellbeing_mapper' } = {}) {
  const aesKey = crypto.randomBytes(32);
  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv('aes-256-gcm', aesKey, iv);
  const ciphertext = Buffer.concat([
    cipher.update(Buffer.from(JSON.stringify(payload), 'utf8')),
    cipher.final(),
    cipher.getAuthTag(),
  ]);
  const encryptedKey = crypto.publicEncrypt(
    { key: publicKeyPem, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
    Buffer.from(aesKey.toString('base64'), 'utf8'),
  );
  const envelope = {
    encryptedData: ciphertext.toString('base64'),
    iv: iv.toString('base64'),
    encryptedKey: encryptedKey.toString('base64'),
    algorithm: ALGORITHM,
    researchSite,
    timestamp: new Date().toISOString(),
  };
  return Buffer.from(JSON.stringify(envelope), 'utf8').toString('base64');
}

/** The body the app posts to /surveys/encrypted or /consent/encrypted. */
function requestBody(surveyType, payload, publicKeyPem, { submissionId } = {}) {
  const body = {
    encrypted_data: encryptPackage(payload, publicKeyPem),
    survey_type: surveyType,
    timestamp: new Date().toISOString(),
  };
  if (submissionId) body.submission_id = submissionId;
  return body;
}

function samplePayload(surveyType) {
  return {
    type: surveyType === 'consent' ? 'consent_form' : `${surveyType}_survey`,
    participant_uuid: crypto.randomUUID(),
    survey_id: 1,
    timestamp: new Date().toISOString(),
    data: { sample: true, note: 'generated by tools/encrypt_sample.js' },
    metadata: { app_version: '0.0.0+0', submission_method: 'encrypt_sample' },
  };
}

function main(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i].startsWith('--')) {
      args[argv[i].slice(2)] = argv[i + 1];
      i += 1;
    }
  }
  if (!args['public-key']) {
    console.error('Usage: encrypt_sample.js --public-key <pem> [--type initial|biweekly|consent] '
      + '[--payload <json file>] [--submission-id <64 hex>|auto]');
    process.exit(2);
  }
  const surveyType = args.type || 'initial';
  const publicKeyPem = fs.readFileSync(args['public-key'], 'utf8');
  const payload = args.payload
    ? JSON.parse(fs.readFileSync(args.payload, 'utf8'))
    : samplePayload(surveyType);
  const submissionId = args['submission-id'] === 'auto'
    ? crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex')
    : args['submission-id'];
  process.stdout.write(`${JSON.stringify(requestBody(surveyType, payload, publicKeyPem, { submissionId }))}\n`);
}

if (require.main === module) main(process.argv.slice(2));

module.exports = { ALGORITHM, encryptPackage, requestBody, samplePayload };
